version: '2'
services:
    optisoins-app:
        image: optisoins
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://optisoins-postgresql:5432/optisoins
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    optisoins-postgresql:
        extends:
            file: postgresql.yml
            service: optisoins-postgresql
