version: '2'
services:
    optisoins-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/optisoins/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=optisoins
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
